main: ru.flametaichou.WorldTimeSynch
name: WorldTimeSynch
version: 0.1
author: flametaichou
description:

commands:
   ep:
      description: Основная команда плагина
      permission: worldtimesynch.*
      usage: /wts reload|help
